name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Build and Push Docker Image
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        env:
          IMAGE_NAME: ${{ secrets.DOCKER_REPO }}
        run: |
          # Build the image with a unique tag, semantic version, and tags for dev/prod
          docker build -t $IMAGE_NAME:${{ github.sha }} .
          docker tag $IMAGE_NAME:${{ github.sha }} $IMAGE_NAME:dev

          # Semantic release will handle versioning
          docker tag $IMAGE_NAME:${{ github.sha }} $IMAGE_NAME:latest

          # Push tags to the registry
          docker push $IMAGE_NAME:${{ github.sha }}
          docker push $IMAGE_NAME:dev
          docker push $IMAGE_NAME:latest

  # Run Tests
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          elif [ -f package.json ]; then
            npm install
          else
            echo "No dependencies to install"
          fi

      - name: Run Tests
        run: |
          echo "Running tests..."
          if [ -f pytest.ini ]; then
            pytest
          elif [ -f package.json ]; then
            npm test
          else
            echo "No tests found"
          fi

  # Deploy to Development Environment
  deploy-dev:
    runs-on: ubuntu-latest
    needs: [build-and-push]
    steps:
      - name: Log in to Docker Registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Deploy to Development
        env:
          IMAGE_NAME: ${{ secrets.DOCKER_REPO }}
        run: |
          echo "Deploying to Development Environment..."
          docker pull $IMAGE_NAME:dev
          docker run -d --name sample-app-dev -p 8080:8080 $IMAGE_NAME:dev

  # Deploy to Production Environment
  deploy-prod:
    runs-on: ubuntu-latest
    needs: [deploy-dev]
    steps:
      - name: Log in to Docker Registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Deploy to Production
        env:
          IMAGE_NAME: ${{ secrets.DOCKER_REPO }}
        run: |
          echo "Deploying to Production Environment..."
          docker pull $IMAGE_NAME:latest
          docker run -d --name sample-app-prod -p 80:80 $IMAGE_NAME:latest

  # Rollback Strategy
  rollback:
    runs-on: ubuntu-latest
    if: github.event.inputs.version != null
    steps:
      - name: Log in to Docker Registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Rollback to Previous Version
        env:
          IMAGE_NAME: ${{ secrets.DOCKER_REPO }}
        run: |
          echo "Rolling back to version: ${{ github.event.inputs.version }}"
          docker pull $IMAGE_NAME:${{ github.event.inputs.version }}
          docker stop sample-app-prod || true
          docker rm sample-app-prod || true
          docker run -d --name sample-app-prod -p 80:80 $IMAGE_NAME:${{ github.event.inputs.version }}
