name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Image
        run: |
          docker build -t neebo-app:${{ secrets.DOCKER_REPO }}:${{ github.sha }} .
          docker tag neebo-app:${{ secrets.DOCKER_REPO }}:${{ github.sha }} ${{ secrets.DOCKER_REPO }}:latest
          docker push neebo-app:${{ secrets.DOCKER_REPO }}:${{ github.sha }}
          docker push neebo-app:${{ secrets.DOCKER_REPO }}:latest

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Tests
        run: |
          # Replace with your testing framework commands
          echo "Running tests...Done"

  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Development
        run: |
          docker pull ${{ secrets.DOCKER_REPO }}:dev
          docker run -d -p 8080:8080 ${{ secrets.DOCKER_REPO }}:dev

  deploy-prod:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Production
        if: github.ref == 'refs/heads/main'
        run: |
          docker pull ${{ secrets.DOCKER_REPO }}:prod
          docker run -d -p 80:80 ${{ secrets.DOCKER_REPO }}:prod
