name: CD Workflow

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build -t sample-app:${{ github.sha }} .

      - name: Push to Container Registry
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag sample-app:${{ github.sha }} ${{ secrets.DOCKER_REPO }}:${{ github.sha }}
          docker push ${{ secrets.DOCKER_REPO }}:${{ github.sha }}

      - name: Deploy to Development
        if: github.ref == 'refs/heads/dev'
        run: |
          docker run -d --name sample-app-dev -p 8080:80 ${{ secrets.DOCKER_REPO }}:${{ github.sha }}

      - name: Deploy to Production
        if: github.ref == 'refs/heads/main'
        run: |
          docker run -d --name sample-app-prod -p 80:80 ${{ secrets.DOCKER_REPO }}:${{ github.sha }}
